#%RAML 1.0 Library
usage: This library defines the Canonical Data types used as part of the Awaze integration

uses:
  property: canonical/PropertyDataType.raml
  individual: canonical/IndividualDataType.raml
  company: canonical/CompanyDataType.raml
  common: canonical/CommonDataType.raml
  header: headers/ApiHeaders.raml
