#%RAML 1.0 NamedExample

value:
  masterId: "C1000"
  name: "C1000"
  office: "132"
  serviceType: "200"
  sizeUnit: SQUARE-METERS
  size: 103
  latitude: "51.509865"
  longitude: "-0.118092"
  address:
    street: Offord Rd
    city: copenhagen
    country: Denmark
    postcode: "1050"
  ownerIndividual:
    masterId: "123EE45"
    firstName: "Tom"
    lastName: "Cruise"
    phone: "07433545667"
    email: "myemail@email.com"
  createdDateTime: 2022-05-16T12:40:51Z
  modifiedDateTime: 2022-05-16T12:40:51Z