#%RAML 1.0 NamedExample
value:
  success: false
  apiName: <env>-awaze-mule-x-som
  version: 4.4.0
  correlationId: b2b19890-c73c-11ea-a44d-0a29e1a180a8
  timestamp: 2020-07-16T08:16:49.842Z
  errorDetails:
      code: "500"
      message: Internal Server Error
      additionalInfo: Server encountered an unexpected error